language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
before_install:
  - gem update --system
  - gem update bundler
script: bundle exec rspec spec
cache: bundler
